update:timeoutをintervalに書き換えた
project-HeartLink/HeartLink pull request #16
Opened 2024-10-29 08:50 UTC by tanaka00005

**何秒後かに処理を実行するのではなく、繰り返し実行するようにした**
- setTimeoutを取り消してsetIntervalに変えた。

**ページが遷移してもアラートが出てしまうエラーの解消**
- clearIntervalを取り入れた。

2024-10-29 09:17 UTC, ayuayuyu requested changes
## 本番のものを作って欲しい

2024-10-29 09:17 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> -  const player = "0";
connectが1の時2の時と分岐をもう作ってほしい

2024-10-29 09:17 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> +            setInterval(() => {
ここは、setIntervalではなく、setTimoutにしてほしい
[setTimeoutについて](https://developer.mozilla.org/ja/docs/Web/API/Window/setTimeout)

setIntervalにして欲しいのは、handleSubmit関数を実行するとき
setTimeoutは一度だけ指定時間後に実行、setIntervalは指定時間後何回も
そのため、最初にconnectが1の時にしか反映されない
試しに1度実行された後にconnectもしくは次の画面に遷移をしても
alertは表示されてしまっている

2024-10-29 09:17 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> +                window.location.reload();
` window.location.reload();`
はなんのために再読み込みをしているの？

2024-10-29 09:17 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> +            }, 5 * 1000);
いくらテストでも5秒は早すぎる

2024-10-30 08:50 UTC, tanaka00005 commented
- 本番想定をして、connectの値を変えた時にも処理を行えるようにした

2024-10-30 09:13 UTC, ayuayuyu requested changes

2024-10-30 09:13 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> +          if (data.connect == 2) {
これは、僕の説明不足でしたすいません。
string型にして欲しいです"2"

2024-10-30 09:13 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> +          else if(data.connect == 0){
以下略 string

2024-10-30 09:13 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> +    const timeout = setInterval(handleSubmit, 20 * 1000);
変数名を`interval`の方がわかりやすいので変更をお願いします。

2024-10-30 09:13 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> +    const timeout = setInterval(handleSubmit, 20 * 1000);
こっちは実行をする方なので5秒間隔にして欲しいです

2024-10-30 09:19 UTC, tanaka00005 commented
- 指導点を直しました。

2024-10-30 09:47 UTC, tanaka00005 commented
- 細かいミスを修正した

2024-10-30 10:42 UTC, ayuayuyu approved these changes

2024-10-30 10:44 UTC, ayuayuyu approved these changes

2024-10-30 10:44 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
>          console.log("data", data);
いいね

2024-10-31 00:32 UTC, mizunoryuki commented
プルリクエストを承認しますね

2024-10-31 00:32 UTC, merged