Feature websocket average
project-HeartLink/HeartLink pull request #20
Opened 2024-10-31 10:39 UTC by tanaka00005

**平均値を計算するようにした**
- websocketで心拍を取得した。
- 配列に入れた。（今は取得した平均値を見たいため、配列に初期値を入れている）
- player1と2のときで、取得する心拍をかえた。
- 心拍の平均値を求めた。

2024-11-01 00:56 UTC, ayuayuyu requested changes
### 気になること

```
const sendPlayerInfo = () => {
    const data = { player: selectedPlayer, name: name }; // dataを正しい形式で設定

    console.log("ただいま、メールを送信してます", data);
    const url = "https://hartlink-api.onrender.com/sendname";

    fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    })
      .then((response) => {
        if (!response.ok) {
          throw new Error("ネットワーク応答が正常ではありません");
        }
        return response.json();
      })
      .then((data) => {
        console.log("Success:", data);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  };
  ```
  これはどこにやった？

2024-11-01 00:56 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +        SaveHeartBeat.push(data.heartRate1);
```
        SaveHeartBeat.push(data.heartRate1);
 ```
 よりも
```
SaveHeartBeat((prev) => [...prev, heartRate1]);

```
の方がデータが安全だからこっちの方がいい

### 参考
[これを読んでみるとわかると思う](https://zenn.dev/yutabeee/articles/99393031e51087)

2024-11-01 00:56 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +  const [heartBeat, setHeartBeat] = useState([]);
```
const [heartBeat, setHeartBeat] = useState([]);

```
はなんのために使うもの？

もし、今後使うとかならコメントで書いてくれると助かる

2024-11-01 00:56 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +  let averageHeartbeat = 0;
細かいことだけど
```
let avgHeartBeat = 0
```
の方が変数名としてわかりやすいから
変更してくれると助かる

2024-11-01 00:56 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +  const location = useLocation(); //location.stateでhistory.pushの引数で渡したstateを取り出すことができる
```
const location = useLocation();
```
なんだけどどこで使っているかがわからない。
```
const 変数名 = location.pathname;
```
という使い方だよね
[Locationの使い方](https://zenn.dev/kkoisland/articles/6284de6a50c442)

何を撮る時に使う想定なのかを教えてほしい

2024-11-03 18:28 UTC, mizunoryuki commented on src/pages/prepare/ShowAvgDatapage.jsx
> +  const location = useLocation(); //location.stateでhistory.pushの引数で渡したstateを取り出すことができる
解決してたらすまん
このコードだとuseLocationつかってないけど用途としては
useNavigateで遷移先のページに送ったstateを取得するための関数だと思う
```prevpage.jsx
   navigate("/getAverage", { state: { selectedPlayer } });
```
location.stateをしてあげると、遷移前のページでnavigateの引数として指定したstate(selectedPlayer)を受け取ることができる
[useLocationのpathnameを取る使い方ではなくstateを受け取る使い方](https://zenn.dev/horisan/articles/2aeaf0bd3fb70f)
多分これをしたかったんじゃないかな

2024-11-04 04:28 UTC, tanaka00005 commented on src/pages/prepare/ShowAvgDatapage.jsx
> +  let averageHeartbeat = 0;
了解
avgHeartBeatに変えました

2024-11-04 04:28 UTC, tanaka00005 commented on src/pages/prepare/ShowAvgDatapage.jsx
> +  let averageHeartbeat = 0;
了解
avHeartBeatに変えました

2024-11-04 04:29 UTC, tanaka00005 commented on src/pages/prepare/ShowAvgDatapage.jsx
> +  const [heartBeat, setHeartBeat] = useState([]);
ごめんなさい、使わないので消しました

2024-11-04 04:38 UTC, tanaka00005 commented on src/pages/prepare/ShowAvgDatapage.jsx
> +  const location = useLocation(); //location.stateでhistory.pushの引数で渡したstateを取り出すことができる
そうだね、りゅうきくんの言う通り、navigateで送ってlocationでstateを受け取ってた時に使った処理です
今は、書き換えちゃったから使ってないので消しときます
[【React】useLocateの使い方](https://qiita.com/yowayowa_engineer/items/d00c2ad7ca5f18d4b526)
私はこれ見て書いた

2024-11-04 04:52 UTC, tanaka00005 commented on src/pages/prepare/ShowAvgDatapage.jsx
> +        SaveHeartBeat.push(data.heartRate1);
なるほど勉強になります。
直しとくね

2024-11-04 04:59 UTC, tanaka00005 commented on src/pages/prepare/ShowAvgDatapage.jsx
> +        SaveHeartBeat.push(data.heartRate1);
heartRate1だけじゃ値のタイプエラーが起きたから
data.heartRate1にしといた

2024-11-04 09:03 UTC, tanaka00005 commented
**リプの分と合計の出し方をreduceを出して求めた。
- reduceで合計を求め、SaveHeartBeat.lengthで割って平均を求めた

2024-11-04 10:19 UTC, tanaka00005 commented
- reduceの処理ができなかったため、使えるようにuseStateに変えた

2024-11-04 11:05 UTC, ayuayuyu requested changes
変更をお願いします

2024-11-04 11:05 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +      const sum = SaveHeartBeat.reduce((acc, cur) => parseInt(acc,10) + parseInt(cur,10)); //objectからint型に変えて、合計を求めた
```
      const sum = SaveHeartBeat.reduce((acc, cur) => parseInt(acc,10) + parseInt(cur,10)); //objectからint型に変えて、合計を求めた

      console.log("sum:", sum);
      const avgHeartBeat = sum / SaveHeartBeat.length;
      ```
      なんだけど結局player1,player2といるわけだから
      関数にして欲しい

2024-11-04 11:05 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +      const sum = SaveHeartBeat.reduce((acc, cur) => parseInt(acc,10) + parseInt(cur,10)); //objectからint型に変えて、合計を求めた
処理はそのままで大丈夫

2024-11-04 15:28 UTC, tanaka00005 commented
**関数に変えました**

2024-11-04 16:57 UTC, ayuayuyu requested changes
変更をお願いします

2024-11-04 16:57 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +
処理は大丈夫だけど
変数名がおかしいかな
今回は平均を求めているから`sum`より`avg`かな
関数の中の`s`は`sumにして
return の部分に　`sum / SaveHeartBeat.length`
にするとコードも短くなって良いかも！

あと `let s`のところだけど `const`でできると思う

2024-11-04 16:58 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +
あと関数の引数に配列を入れるといいと思う
今回ならSaveHeartBeatを関数を呼び出すときに
関数(SaveHeartBeat)にして使えるようにして欲しい

2024-11-05 01:53 UTC, tanaka00005 commented on src/pages/prepare/ShowAvgDatapage.jsx
> +
変数名直し忘れてた、気をつけます。
引数のとこも直しといた

2024-11-05 01:54 UTC, tanaka00005 commented
- 関数のところを直しときました

2024-11-05 01:58 UTC, ayuayuyu approved these changes
変更をお願いします

2024-11-05 01:58 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +      function avg(SaveHeartBeat) {
ここの引数は
`heartBeat`のほうがいいと思う
SaveHeartBeatの変数の値を使っていると考えるため

2024-11-05 01:58 UTC, ayuayuyu commented on src/pages/prepare/ShowAvgDatapage.jsx
> +      function avg(SaveHeartBeat) {
使う時に avg(SaveHeartBeat)として使えばいい

2024-11-05 01:59 UTC, ayuayuyu requested changes
変更をお願いします

2024-11-05 02:03 UTC, tanaka00005 commented on src/pages/prepare/ShowAvgDatapage.jsx
> +      function avg(SaveHeartBeat) {
了解

2024-11-05 02:03 UTC, tanaka00005 commented
- 関数の引数名を変えた

2024-11-05 02:05 UTC, ayuayuyu approved these changes
LGTM!

2024-11-05 02:05 UTC, merged