Feature theme choice
project-HeartLink/HeartLink pull request #25
Opened 2024-11-07 05:24 UTC by tanaka00005

**selectThemepage**
- https通信をして選択したテーマを送る
- 選択したplayerにあったお題を画面表示させる（偶数か奇数で分けた)
**mainpage**
- websocketでidを取得
- selectThemepageで取得したidと照らし合わせてテーマを表示
- 配列が終わったら終了画面へ

2024-11-07 07:37 UTC, ayuayuyu requested changes
変更をお願いします

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +import React, { useState, useEffect } from "react";
`React, `
は消してくね！
`useState`または`useEffect`を使う場合は
`import { useState, useEffect } from "react";`
でいいよ

これは、過去の産物
[import Reactはもういらない](https://qiita.com/Yz_4230/items/ce70927d36f7a6cf619d)

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const socketRef = React.useRef();
直してね

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const [message, setMessage] = React.useState();
以下略

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +      const data = JSON.parse(event.data);
destrを使って欲しい

今までいうの忘れていた
ごめんなさい

[destrとは](https://deno.land/x/destr@v1.0.0)

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/prepare/SelectPlayerpage.jsx
> -  const sendPlayerInfo = () => {
どうして消した？

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +      body: JSON.stringify(data),
以下略

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +      eventSelect.push(theme);
コールバック関数を使ってね

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +                onClick={FinishTheme}
`onClick={()=>FinishTheme}`のほうがいいね

2024-11-07 07:37 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +      for (let i = 0; i < data.topicId.length; i++) {
別関数にして表示するようにして

2024-11-07 07:45 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +import React, { useState, useEffect } from "react";
直しました

2024-11-07 07:46 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const socketRef = React.useRef();
直しました

2024-11-07 07:46 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const [message, setMessage] = React.useState();
直しました

2024-11-07 11:31 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +      const data = JSON.parse(event.data);
教えてくれてありがとう。できました

2024-11-08 02:21 UTC, tanaka00005 commented
言われたところ直しました

2024-11-08 08:22 UTC, tanaka00005 commented on src/pages/main/selectThemepage.jsx
> +      eventSelect.push(theme);
const [eventSelect, setEventSelect] = useState([]); //player1
  const [oddSelect, setOddSelect] = useState([]); //player2

  useEffect(() => {
    setEventSelect(themes.filter((theme) => theme.id % 2 == 0));

    setOddSelect(themes.filter((theme) => theme.id % 2 != 0));
  }, []);

  のように書き換えたんだけど、スプレット構文にしたほうがいい？

2024-11-08 08:29 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +      for (let i = 0; i < data.topicId.length; i++) {
引数とかは？

2024-11-08 08:29 UTC, tanaka00005 commented on src/pages/main/selectThemepage.jsx
> +      body: JSON.stringify(data),
なんの？

2024-11-08 08:53 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +      body: JSON.stringify(data),
これは違うわ
ごめん

2024-11-08 09:09 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +      eventSelect.push(theme);
これでいいよ

2024-11-08 09:09 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +      for (let i = 0; i < data.topicId.length; i++) {
id をだけでいいかな

2024-11-09 05:31 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +      for (let i = 0; i < data.topicId.length; i++) {
了解

2024-11-09 05:37 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +                onClick={FinishTheme}
了解

2024-11-09 05:54 UTC, tanaka00005 commented on src/pages/prepare/SelectPlayerpage.jsx
> -  const sendPlayerInfo = () => {
マージされてない状態のブランチから生やしたからなかった
その時の処理を丸ごとコピペしたきたよ

2024-11-09 06:03 UTC, ayuayuyu requested changes

2024-11-09 06:03 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +    websocket.addEventListener("open", () => {
ここ(` websocket.addEventListener`)なんだけど
`websocket.open`でいいと思う
以下が参考文献

[WebSocket通信](https://grafana.com/docs/k6/latest/javascript-api/k6-experimental/websockets/websocket/websocket-addeventlistener/)

2024-11-09 06:29 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +    websocket.addEventListener("open", () => {
ありがとう変えました。

2024-11-09 06:31 UTC, tanaka00005 commented
- 指摘されたとこ修正しました。確認お願いします

2024-11-09 07:25 UTC, ayuayuyu requested changes
変更をお願いします

2024-11-09 07:25 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +    { id: 0, topic: "相手に対して今感じていることを素直に話す" },
この配列を別のファイルに作って欲しい
それをimportして配列を使って欲しい

そうすることで新しくコードが短くなるしlocationで持ってこなくてもすむ

2024-11-09 07:25 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +export const SelectTheme = ({ player }) => {
playerに何も入っていないから強制的に2の選択しかなくなっている
player1の時の選択肢が表示されない

2024-11-09 07:25 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +            {selectPlayer.map((theme, index) => (
`key={index}`
のところ
`key={theme.id}`の方がいいと思う

2024-11-09 07:25 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +      function wsTheme (id) {
下の方に書いてあるんだけど
`themes`を別ファイルにして
それをimportして使って欲しい

locationではなく

2024-11-10 12:14 UTC, tanaka00005 commented on src/pages/main/selectThemepage.jsx
> +    { id: 0, topic: "相手に対して今感じていることを素直に話す" },
mainpageの方で、locationで受け取らなくて済むってことだよね？

2024-11-10 12:16 UTC, tanaka00005 commented on src/pages/main/selectThemepage.jsx
> +            {selectPlayer.map((theme, index) => (
了解

2024-11-10 12:18 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +      function wsTheme (id) {
了解

2024-11-10 12:18 UTC, tanaka00005 commented on src/pages/main/selectThemepage.jsx
> +export const SelectTheme = ({ player }) => {
了解

2024-11-10 12:19 UTC, tanaka00005 commented
指摘部分直したよ。確認お願いします

2024-11-10 13:50 UTC, ayuayuyu approved these changes
LGTM!

2024-11-10 15:30 UTC, merged