Feature fix ws
project-HeartLink/HeartLink pull request #40
Opened 2024-11-16 10:31 UTC by tanaka00005

**mainpage**
- お題を出す方法を変えた
- 各お題ごとに心拍を分けて、配列に格納させる
- getでendを送る

**heart-beat**
- ハートのアニメーションを取り入れた

**resultpage**
- playerの値を取ってくる

2024-11-16 11:01 UTC, tanaka00005 commented
ごめんなさい。できてない処理があったのでもう一度プルリク送ります。
さっきのと変更点は、お題ごとにtheme1,theme2...で格納していくのに加えて、それを数字で表せるようにしました。あと、player情報でPlayer1,Player2を返すのではなく"1"or"2"を返すようにした。

2024-11-16 16:18 UTC, ayuayuyu requested changes
変更をお願いします。

mainpageとresultpageはあまり見ていないです。
変更をする予定なので

2024-11-16 16:18 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +        setArrHeartBeatTheme({ ...arrHeartBeatTheme, theme1: data.heartRate1 });
ここはコールバック関数を使った方がいいと思う
[コールバック関数](https://zenn.dev/sprout2000/books/76a279bb90c3f3/viewer/chapter07)

2024-11-16 16:18 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const [arrHeartBeatTheme, setArrHeartBeatTheme] = useState({
これは、それぞれのお題に対して、心拍を格納するものだとは思うけど
配列ではなくて、なぜ、一つの値なの？

2024-11-16 16:18 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
>    const [message, setMessage] = useState();
`message`を使っていないなら消してほしい。
前回見逃した僕の責任でもあります。

2024-11-16 16:18 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const [heartBeatP1, setHeartBeatP1] = useState();
`setHeartBeatP1`はどこで使っていますか？

2024-11-16 16:18 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +      setarrThemes(themes[data.topicId[0]].topic); //mainpageに遷移した直後にお題を写るように
` setarrThemes(themes[data.topicId[0]].topic); `
のindexはWebSocketで送ったからそれを使用してね♡
とした方がいいかも

2024-11-16 16:18 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +        setArrHeartBeatTheme({ ...arrHeartBeatTheme, theme1: data.heartRate1 });
どうやってとるか検討がつかない

2024-11-16 16:18 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +    if (indexplayer == 0) {
なぜ、それぞれの時行うのに` if `をそれぞれしてるの？

それならば or 文`if(indexplayer == 0 || indexplayer == 1)`
にしてほしい

2024-11-17 03:37 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
>    const [message, setMessage] = useState();
了解、消したよ

2024-11-17 03:37 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const [heartBeatP1, setHeartBeatP1] = useState();
使ってません。消したよ

2024-11-17 03:37 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const [arrHeartBeatTheme, setArrHeartBeatTheme] = useState({
オブジェクトの使い方を理解してませんでした。配列にしました。

2024-11-17 11:14 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +        setArrHeartBeatTheme({ ...arrHeartBeatTheme, theme1: data.heartRate1 });
多分できたと思う

2024-11-17 15:59 UTC, tanaka00005 commented on src/pages/main/selectThemepage.jsx
> +    if (indexplayer == 0) {
正直、日本語の意味がわからないからif(indexplayer == 0 || indexplayer == 1){}
という感じに書き換えました
何かあったらまた言ってください

2024-11-20 07:43 UTC, tanaka00005 commented
- 主にサーバー側との接続をしました。

2024-11-20 07:45 UTC, tanaka00005 commented
- 主にサーバー側との接続をしました

2024-11-20 08:08 UTC, ayuayuyu requested changes
変更をお願いします

2024-11-20 08:08 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const [heartBeatP1, setHeartBeatP1] = useState([]);
`const [heartBeatP1, setHeartBeatP1] = useState([]);`は配列なのに
`const [heartBeatP2, setHeartBeatP2] = useState();`は配列ではないの？
また、一緒にまとめてくれると助かります

2024-11-20 08:08 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +      console.log("heartRate2", data.heartRate1);
`"heartRate2"`は`"heartRate1"`では？

2024-11-20 08:08 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const [player1Name, setPlayr1Name] = useState();
useStateにstrを入れるのならば初期値に("")に入れた方がいいと思う

2024-11-20 08:08 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +      setProIndex(data.index); //data.indexだったら、前の段階の値が帰ってくるから(proindexの値が0から始まる)から無理やり+1にした
いらないコメントは消そう

2024-11-20 08:08 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +      console.log("data.topicId", data.topicId[2]);
なぜ、topicIdが2の時だけなの？
現在のindexで見ればいいと思う

2024-11-20 09:09 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const [player1Name, setPlayr1Name] = useState();
了解

2024-11-20 09:12 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +      console.log("heartRate2", data.heartRate1);
その通りです。消しときました

2024-11-20 09:12 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +      setProIndex(data.index); //data.indexだったら、前の段階の値が帰ってくるから(proindexの値が0から始まる)から無理やり+1にした
了解

2024-11-20 09:12 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +      console.log("data.topicId", data.topicId[2]);
了解

2024-11-20 09:28 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const [heartBeatP1, setHeartBeatP1] = useState([]);
了解

2024-11-20 09:31 UTC, tanaka00005 commented
変更直しました

2024-11-20 10:13 UTC, ayuayuyu requested changes
変更をお願いします

2024-11-20 10:13 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const [heartBeatP1, setHeartBeatP1] = useState([]);
ok

2024-11-20 10:13 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const [player2Name, setPlayr2Name] = useState();
これもです("")

2024-11-20 10:13 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const heartBeatSet = ["123", "113", "99", "123", "89"];
この配列もういらないよね

2024-11-20 10:17 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const heartBeatSet = ["123", "113", "99", "123", "89"];
消しときました

2024-11-20 10:20 UTC, tanaka00005 commented
いらない処理を消したのと、レビューの修正をしました

2024-11-20 11:08 UTC, ayuayuyu approved these changes
LGTM!

2024-11-20 11:31 UTC, merged