Logic result success
project-HeartLink/HeartLink pull request #46
Opened 2024-11-21 11:41 UTC by tanaka00005

- https://hartlink-api.onrender.com/getTopicArrayで心拍を取得
- playerの名前と心拍の配列をメインページから受け渡す
- 最大値の計算
- グラフへの変換の配列

2024-11-22 02:22 UTC, tanaka00005 commented
- 最大心拍のお題の書き方を変えた

2024-11-22 07:12 UTC, tanaka00005 commented
コメントつけました。keyとかの処理がややこしいので、わからなかったら聞いてほしい。

2024-11-22 14:09 UTC, ayuayuyu requested changes
変更をお願いします

2024-11-22 14:09 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
>    const [proIndex, setProIndex] = useState();
初期化して欲しいです。

2024-11-22 14:09 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const [arrSelectTopic,setArrSelectTopic] = useState()
初期化して欲しいです。

2024-11-22 14:09 UTC, ayuayuyu commented on src/pages/result/resultpage.jsx
>    const [player1, setPlayer1] = useState();
初期化をしてください

2024-11-22 14:09 UTC, ayuayuyu commented on src/pages/result/resultpage.jsx
>    const [player2, setPlayer2] = useState();
初期化してください

2024-11-22 14:09 UTC, ayuayuyu commented on src/pages/result/resultpage.jsx
>    const [showId, setShowId] = useState();
初期化をしてください

2024-11-22 14:09 UTC, ayuayuyu commented on src/pages/result/resultpage.jsx
> +    //player1の選択したお題の心拍とお題の格納
こっちもplayer1なの？

2024-11-22 14:09 UTC, ayuayuyu commented on src/pages/result/resultpage.jsx
> +  const themes = themesArr; //locateで値を受け取る
location?

どこから設定してる？

2024-11-23 09:02 UTC, tanaka00005 commented on src/pages/result/resultpage.jsx
> +  const themes = themesArr; //locateで値を受け取る
mainページから

2024-11-23 09:33 UTC, tanaka00005 commented on src/pages/result/resultpage.jsx
> +    //player1の選択したお題の心拍とお題の格納
ごめんなさい。直しました

2024-11-23 09:34 UTC, tanaka00005 commented on src/pages/result/resultpage.jsx
>    const [player2, setPlayer2] = useState();
いらなかったから消した

2024-11-23 09:34 UTC, tanaka00005 commented on src/pages/result/resultpage.jsx
>    const [player1, setPlayer1] = useState();
いらなかったから消した

2024-11-23 09:34 UTC, tanaka00005 commented on src/pages/result/resultpage.jsx
>    const [showId, setShowId] = useState();
してるくない？

2024-11-23 09:35 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
>    const [proIndex, setProIndex] = useState();
了解

2024-11-23 09:35 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const [arrSelectTopic,setArrSelectTopic] = useState()
りょうかい

2024-11-23 09:35 UTC, tanaka00005 commented
修正したので見てみてほしい

2024-11-23 10:36 UTC, ayuayuyu approved these changes
LGTM!

2024-11-23 11:26 UTC, merged