Fix component
project-HeartLink/HeartLink pull request #62
Opened 2024-12-13 03:10 UTC by tanaka00005

## ResponseMethod
通信系の処理をまとめた

## Calculation
最大値などの計算系をまとめた

2024-12-30 07:32 UTC, ayuayuyu requested changes
変更をお願いします

2024-12-30 07:32 UTC, ayuayuyu commented on src/response/ResponseMethod.jsx
> +export const getMethod = (link) => {
exportしているから最初は大文字がいいと思う

2024-12-30 07:32 UTC, ayuayuyu commented on src/response/ResponseMethod.jsx
> +export const postMethod = (link, data) => {
上に同じ

2024-12-30 07:32 UTC, ayuayuyu commented on src/response/ResponseMethod.jsx
> +export const websocketMethod = () => {
上に同じ

2024-12-30 07:51 UTC, tanaka00005 commented on src/response/ResponseMethod.jsx
> +export const getMethod = (link) => {
了解

2024-12-30 07:51 UTC, tanaka00005 commented on src/response/ResponseMethod.jsx
> +export const postMethod = (link, data) => {
了解

2024-12-30 07:51 UTC, tanaka00005 commented on src/response/ResponseMethod.jsx
> +export const websocketMethod = () => {
了解

2024-12-30 07:52 UTC, tanaka00005 commented
レビューしたとこ直しました

2024-12-30 15:25 UTC, ayuayuyu requested changes
変更をお願いします

2024-12-30 15:25 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
> +import { getMethod } from "../../response/ResponseMethod";
大文字に変わったのならばここも変えてほし

2024-12-30 15:25 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +import { getMethod, postMethod, websocketMethod } from "../../response/ResponseMethod";
上に同じ

2024-12-30 15:25 UTC, ayuayuyu commented on src/pages/main/selectThemepage.jsx
> +import { postMethod } from "../../response/ResponseMethod";
上に同じ

2024-12-30 15:25 UTC, ayuayuyu commented on src/pages/prepare/SelectPlayerpage.jsx
> +import { getMethod, postMethod } from "../../response/ResponseMethod";
上に同じ

2024-12-30 15:25 UTC, ayuayuyu commented on src/pages/result/resultpage.jsx
> +import { getMethod } from "../../response/ResponseMethod";
上に同じ

2024-12-31 08:44 UTC, tanaka00005 commented on src/pages/connect/Connectpage.jsx
> +import { getMethod } from "../../response/ResponseMethod";
忘れてた
直します

2024-12-31 08:51 UTC, tanaka00005 commented
名称全部直した

2024-12-31 14:46 UTC, ayuayuyu requested changes
変更をお願いします

2024-12-31 14:46 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +  const SpeedChanger2 = (heartRate) => {
exportして使わないのならばこれは小文字でいいよ

2024-12-31 14:46 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +    SpeedChanger1(data.heartRate1);
上に同じ

2024-12-31 14:46 UTC, ayuayuyu commented on src/pages/main/mainpage.jsx
> +    SpeedChanger2(data.heartRate2);
以上同様

2025-01-02 06:34 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +  const SpeedChanger2 = (heartRate) => {
了解

2025-01-02 06:36 UTC, tanaka00005 commented on src/pages/main/mainpage.jsx
> +import { getMethod, postMethod, websocketMethod } from "../../response/ResponseMethod";
これはexportして使ってるから大文字でいいんだよね？

2025-01-02 11:49 UTC, tanaka00005 commented
頭文字直しました

2025-01-02 14:32 UTC, ayuayuyu requested changes
教えてください

2025-01-02 14:32 UTC, ayuayuyu commented on src/pages/connect/Connectpage.jsx
>    const handleClose = () => {
handleClose使われている？
handleOpenなら使われrjkgmているけど
どこにある？

2025-01-02 14:47 UTC, tanaka00005 commented on src/pages/prepare/SelectPlayerpage.jsx
> +import { getMethod, postMethod } from "../../response/ResponseMethod";
了解

2025-01-02 14:50 UTC, tanaka00005 commented on src/pages/connect/Connectpage.jsx
>    const handleClose = () => {
106行目と142行目で使われているよ

2025-01-02 14:55 UTC, ayuayuyu approved these changes
LGTM!

2025-01-03 03:00 UTC, merged